# fly.toml app configuration file generated for humus-waste-watcher on 2025-01-03T18:30:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'humus-waste-watcher'
primary_region = 'mad'

[build]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
source = "tracker_db_volume"
destination = "/data"
