name: Deploy to Fly.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          export FLYCTL_INSTALL="/home/runner/.fly"
          export PATH="$FLYCTL_INSTALL/bin:$PATH"
          echo "FLYCTL_INSTALL=$FLYCTL_INSTALL" >> $GITHUB_ENV
          echo "PATH=$PATH" >> $GITHUB_ENV

      - name: Authenticate Flyctl
        run: flyctl auth login --email diogo.dores@gmail.com --password ${{ secrets.FLY_PASSWORD }} --access-token ${{ secrets.FLY_API_TOKEN }}

      - name: Start SFTP session and download database
        run: |
          mkdir data
          flyctl ssh sftp shell -a humus-waste-watcher <<EOF
          get /app/data/poop_tracker.db data/poop_tracker.db
          EOF

      - name: Upload database artifact
        uses: actions/upload-artifact@v4
        with:
          name: poop_tracker_db
          path: data/poop_tracker.db
      
      - name: check stuff
        run: ls -la

      # - name: Deploy to Fly.io
      #   run: flyctl deploy

      # - name: Clean up
      #   run: rm -rf data/poop_tracker.db